language: android

android:
  components:
    - build-tools-29.0.3
    - android-29

script:
  - ./gradlew assembleRelease

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "app/build/outputs/apk/release/app-release.apk"
  skip_cleanup: true
  on:
    tags: true
